spring.application.name=ai-resume-job-matcher

spring.datasource.url=jdbc:mysql://localhost:3306/resume_job_matcher
spring.datasource.username=root
spring.datasource.password=Adi@07#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=hskafhiuofieuriqwv9e93fewjnjdnv9vfeqfnvijfeiffmknef9wfjcwdhhgueu7433
jwt.expiration=86400000

server.port=8080
